name: Space Invader Contributions

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Generate Space Invader Animation
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python generate_space_invader.py
    
    - name: Commit and Push
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add contribution_space_invader.svg
        git commit -m "Update contribution space invader" || echo "No changes to commit"
        git push origin HEAD:main || git push origin HEAD:master