name: Space Invader Contributions

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests svgwrite
    
    - name: Generate Space Invader Animation
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python generate_space_invader.py
    
    - name: Commit and Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update contribution space invader"
        git push
